package client.privateclient.gui;

import client.privateclient.auth.SessionObserver;
import client.privateclient.gui.font.SharpFontRenderer;
import client.privateclient.profile.LocalSkinCache;
import client.privateclient.security.CorePaths;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.lang.reflect.Constructor;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.Optional;
import java.util.UUID;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiButton;
import net.minecraft.client.gui.GuiMultiplayer;
import net.minecraft.client.gui.GuiOptions;
import net.minecraft.client.gui.GuiScreen;
import net.minecraft.client.gui.GuiSelectWorld;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.Tessellator;
import net.minecraft.client.renderer.WorldRenderer;
import net.minecraft.client.renderer.vertex.DefaultVertexFormats;
import net.minecraft.client.renderer.texture.DynamicTexture;
import net.minecraft.client.resources.DefaultPlayerSkin;
import net.minecraft.client.resources.I18n;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.Session;
import net.minecraftforge.fml.client.GuiModList;
import org.lwjgl.opengl.GL11;

/** Monochrome, local-only replacement for Minecraft's stock main menu. */
public final class GuiPrivateMainMenu extends GuiScreen {
    private static final int SINGLEPLAYER = 1;
    private static final int MULTIPLAYER = 2;
    private static final int MODS = 3;
    private static final int OPTIONS = 4;
    private static final int ACCOUNTS = 5;
    private static final int QUIT = 6;
    private static final int BUTTON_SIZE = 30;
    private static final int BUTTON_GAP = 9;
    private static final int BUTTON_COUNT = 6;
    private static final float BACKGROUND_ASPECT = 16.0F / 9.0F;
    private static final long SKIN_RETRY_MILLIS = 2_000L;

    private static final ResourceLocation BACKGROUND =
            new ResourceLocation("privateclientcore", "textures/gui/menu-background.png");
    /**
     * Six glyphs in one row, 128px per cell. Generated by
     * {@code scripts/design/generate-icons.mjs}; do not hand-edit the PNG.
     */
    private static final ResourceLocation ICONS =
            new ResourceLocation("privateclientcore", "textures/gui/menu-icons.png");
    /** Drawn size inside a 30px button, leaving an even margin on every side. */
    private static final int ICON_DRAW_SIZE = 20;
    private static final ResourceLocation LOCAL_SKIN =
            new ResourceLocation("privateclientcore", "dynamic/menu-player-skin");
    /** 1.8.9 has no DefaultPlayerSkin.getDefaultSkinLegacy(); Steve is the safe fallback. */
    private static final ResourceLocation DEFAULT_SKIN =
            new ResourceLocation("textures/entity/steve.png");

    /**
     * Null when font rasterisation was unavailable, in which case every helper
     * below falls back to the vanilla bitmap renderer rather than failing.
     */
    private SharpFontRenderer sharpFont;

    private final SessionObserver sessionObserver;
    // Fixed English locale rather than the system default: the weekday and
    // month names are drawn with the client's own glyph atlas, and a locale
    // picked up from the OS could ask it for glyphs it does not contain.
    private final SimpleDateFormat dateFormat =
            new SimpleDateFormat("EEEE, d MMMM yyyy", Locale.ENGLISH);
    private final SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm", Locale.ROOT);
    private volatile ResourceLocation playerSkin = DEFAULT_SKIN;
    private final LocalSkinCache skinCache = new LocalSkinCache(CorePaths.discover().getDataRoot());
    private UUID loadedSkinProfile;
    private ResourceLocation localSkinTexture;
    private long nextSkinRefreshAt;
    private long nextClockUpdateAt;
    private String displayedDate = "";
    private String displayedTime = "--:--";

    public GuiPrivateMainMenu(SessionObserver sessionObserver) {
        if (sessionObserver == null) {
            throw new IllegalArgumentException("Session observer is required");
        }
        this.sessionObserver = sessionObserver;
    }
    private int hoveredAction = -1;

    @Override
    public void initGui() {
        if (sharpFont == null) {
            sharpFont = SharpFontRenderer.create(mc, "menu");
        }
        buttonList.clear();
        int y = buttonRowY();
        int start = buttonRowStart();
        for (int index = 0; index < BUTTON_COUNT; index++) {
            buttonList.add(new MonochromeIconButton(
                    index + 1,
                    start + index * (BUTTON_SIZE + BUTTON_GAP),
                    y,
                    BUTTON_SIZE,
                    BUTTON_SIZE,
                    index));
        }
        refreshSkin();
    }

    @Override
    protected void actionPerformed(GuiButton button) throws IOException {
        switch (button.id) {
            case SINGLEPLAYER:
                mc.displayGuiScreen(new GuiSelectWorld(this));
                break;
            case MULTIPLAYER:
                mc.displayGuiScreen(new GuiMultiplayer(this));
                break;
            case MODS:
                mc.displayGuiScreen(new GuiModList(this));
                break;
            case OPTIONS:
                mc.displayGuiScreen(new GuiOptions(this, mc.gameSettings));
                break;
            case ACCOUNTS:
                openAccountSwitcher();
                break;
            case QUIT:
                mc.shutdown();
                break;
            default:
                break;
        }
    }

    @Override
    public void drawScreen(int mouseX, int mouseY, float partialTicks) {
        drawCoverBackground();
        drawRect(0, 0, width, height, 0x59000000);
        drawBranding();
        drawClock();
        ensureSkinMatchesSession();
        drawProfileCard();

        hoveredAction = -1;
        super.drawScreen(mouseX, mouseY, partialTicks);
        drawHoveredAction();
    }

    @Override
    public boolean doesGuiPauseGame() {
        return false;
    }

    @Override
    public void onGuiClosed() {
        clearLocalSkinTexture();
        super.onGuiClosed();
    }

    private void drawCoverBackground() {
        mc.getTextureManager().bindTexture(BACKGROUND);
        GlStateManager.color(1.0F, 1.0F, 1.0F, 1.0F);

        float screenAspect = height == 0 ? BACKGROUND_ASPECT : width / (float) height;
        float u0 = 0.0F;
        float u1 = 1.0F;
        float v0 = 0.0F;
        float v1 = 1.0F;
        if (screenAspect > BACKGROUND_ASPECT) {
            float span = BACKGROUND_ASPECT / screenAspect;
            v0 = (1.0F - span) / 2.0F;
            v1 = v0 + span;
        } else {
            float span = screenAspect / BACKGROUND_ASPECT;
            u0 = (1.0F - span) / 2.0F;
            u1 = u0 + span;
        }

        Tessellator tessellator = Tessellator.getInstance();
        WorldRenderer renderer = tessellator.getWorldRenderer();
        renderer.begin(7, DefaultVertexFormats.POSITION_TEX);
        renderer.pos(0.0D, height, 0.0D).tex(u0, v1).endVertex();
        renderer.pos(width, height, 0.0D).tex(u1, v1).endVertex();
        renderer.pos(width, 0.0D, 0.0D).tex(u1, v0).endVertex();
        renderer.pos(0.0D, 0.0D, 0.0D).tex(u0, v0).endVertex();
        tessellator.draw();
    }

    /** Draws text with the sharp renderer, falling back to the bitmap font. */
    private void text(String value, int x, int y, float size, int color) {
        if (sharpFont == null) {
            drawString(fontRendererObj, value, x, y, color);
            return;
        }
        sharpFont.draw(value, x, y, size, color);
    }

    private void textCentered(String value, int centerX, int y, float size, int color) {
        if (sharpFont == null) {
            drawCenteredString(fontRendererObj, value, centerX, y, color);
            return;
        }
        sharpFont.drawCentered(value, centerX, y, size, color);
    }

    private void drawBranding() {
        text("PRIVATE CLIENT", 10, 10, 12.0F, 0xFFF5F5F5);
    }

    private void drawClock() {
        int dateY = Math.max(34, height / 2 - 100);
        long now = System.currentTimeMillis();
        if (now >= nextClockUpdateAt) {
            Date instant = new Date(now);
            displayedDate = dateFormat.format(instant);
            displayedTime = timeFormat.format(instant);
            nextClockUpdateAt = now + 1_000L;
        }
        textCentered(displayedDate, width / 2, dateY, 12.0F, 0xFF999999);

        // Drawn at its real size rather than scaled up from the 8px bitmap
        // font, which is what used to turn every glyph pixel into a 3x3 block.
        // Digits are tabular, so the clock does not shift as the minute rolls.
        textCentered(displayedTime, width / 2, dateY + 18, 34.0F, 0xFFF4F4F4);
    }

    private void drawProfileCard() {
        int cardWidth = 236;
        int cardHeight = 46;
        int x = width / 2 - cardWidth / 2;
        int y = profileCardY();
        drawRect(x, y, x + cardWidth, y + cardHeight, 0xD20A0A0A);
        drawHorizontalLine(x, x + cardWidth, y, 0xFF555555);
        drawHorizontalLine(x, x + cardWidth, y + cardHeight, 0xFF202020);

        mc.getTextureManager().bindTexture(playerSkin);
        GlStateManager.color(1.0F, 1.0F, 1.0F, 1.0F);
        GlStateManager.enableBlend();
        GlStateManager.tryBlendFuncSeparate(770, 771, 1, 0);
        try {
            drawScaledCustomSizeModalRect(x + 7, y + 7, 8.0F, 8.0F,
                    8, 8, 32, 32, 64.0F, 64.0F);
            drawScaledCustomSizeModalRect(x + 7, y + 7, 40.0F, 8.0F,
                    8, 8, 32, 32, 64.0F, 64.0F);
        } finally {
            GlStateManager.disableBlend();
        }

        Session session = mc.getSession();
        String username = session == null || session.getUsername() == null
                ? "Unknown player" : session.getUsername();
        text(username, x + 48, y + 10, 14.0F, 0xFFFFFFFF);
        text(accountKind(), x + 48, y + 27, 11.0F, 0xFFAAAAAA);
    }

    private String accountKind() {
        return sessionObserver.getValidation().isAuthenticated()
                ? "PREMIUM" : "NON-PREMIUM";
    }

    private void ensureSkinMatchesSession() {
        Session session = mc.getSession();
        UUID current = session == null || session.getProfile() == null
                ? null : session.getProfile().getId();
        if (current == null ? loadedSkinProfile != null : !current.equals(loadedSkinProfile)) {
            refreshSkin();
        } else if (current != null && localSkinTexture == null
                && System.currentTimeMillis() >= nextSkinRefreshAt) {
            refreshSkin();
        }
    }

    private void refreshSkin() {
        Session session = mc.getSession();
        final UUID profileId = session == null || session.getProfile() == null
                ? null : session.getProfile().getId();
        clearLocalSkinTexture();
        loadedSkinProfile = profileId;
        playerSkin = profileId == null
                ? DEFAULT_SKIN
                : DefaultPlayerSkin.getDefaultSkin(profileId);
        nextSkinRefreshAt = System.currentTimeMillis() + SKIN_RETRY_MILLIS;
        if (profileId == null) {
            return;
        }
        try {
            Optional<BufferedImage> cached = skinCache.load(profileId);
            if (cached.isPresent()) {
                mc.getTextureManager().loadTexture(
                        LOCAL_SKIN, new DynamicTexture(cached.get()));
                localSkinTexture = LOCAL_SKIN;
                playerSkin = LOCAL_SKIN;
            }
        } catch (IOException ignored) {
            // Keep the UUID-derived vanilla fallback; retry after the bounded delay.
        }
    }

    private void clearLocalSkinTexture() {
        if (localSkinTexture != null) {
            mc.getTextureManager().deleteTexture(localSkinTexture);
            localSkinTexture = null;
        }
    }

    private void openAccountSwitcher() {
        try {
            Class<?> screenClass = Class.forName("the_fireplace.ias.gui.GuiAccountSelector");
            Constructor<?> constructor = screenClass.getConstructor(GuiScreen.class);
            Object screen = constructor.newInstance(this);
            if (screen instanceof GuiScreen) {
                mc.displayGuiScreen((GuiScreen) screen);
                return;
            }
        } catch (ReflectiveOperationException ignored) {
            // The pinned external mod may be absent in a development instance.
        }
        mc.displayGuiScreen(new GuiMessage(this, "Account Switcher",
                "In-Game Account Switcher is not loaded."));
    }

    private int profileCardY() {
        int ideal = Math.max(94, height / 2 - 12);
        return Math.min(ideal, Math.max(82, height - 108));
    }

    private int buttonRowY() {
        return Math.min(profileCardY() + 56, height - 56);
    }

    private int buttonRowStart() {
        int rowWidth = BUTTON_COUNT * BUTTON_SIZE + (BUTTON_COUNT - 1) * BUTTON_GAP;
        return width / 2 - rowWidth / 2;
    }

    private void drawHoveredAction() {
        if (hoveredAction < 0) {
            return;
        }
        String[] labels = {"Singleplayer", "Multiplayer", "Mods", "Options", "Accounts", "Quit"};
        textCentered(labels[hoveredAction], width / 2,
                Math.min(buttonRowY() + 38, height - 26), 12.0F, 0xFFE4E4E4);
    }

    private final class MonochromeIconButton extends GuiButton {
        private final int icon;

        private MonochromeIconButton(
                int id, int x, int y, int width, int height, int icon) {
            super(id, x, y, width, height, "");
            this.icon = icon;
        }

        @Override
        public void drawButton(Minecraft minecraft, int mouseX, int mouseY) {
            if (!visible) {
                return;
            }
            hovered = mouseX >= xPosition && mouseY >= yPosition
                    && mouseX < xPosition + width && mouseY < yPosition + height;
            if (hovered) {
                hoveredAction = icon;
            }
            int fill = hovered ? 0xFFEDEDED : 0xD2141414;
            int stroke = hovered ? 0xFFFFFFFF : 0xFF5A5A5A;
            int glyph = hovered ? 0xFF0A0A0A : 0xFFE8E8E8;
            drawRect(xPosition, yPosition, xPosition + width, yPosition + height, fill);
            drawHorizontalLine(xPosition, xPosition + width, yPosition, stroke);
            drawHorizontalLine(xPosition, xPosition + width, yPosition + height, stroke);
            drawVerticalLine(xPosition, yPosition, yPosition + height, stroke);
            drawVerticalLine(xPosition + width, yPosition, yPosition + height, stroke);
            drawIcon(icon, xPosition + width / 2, yPosition + height / 2, glyph);
        }
    }

    /**
     * Draws the glyph for a menu action from the icon atlas.
     *
     * <p>These used to be assembled from {@code drawRect} primitives, one
     * scanline per row of a circle. That has no antialiasing by construction,
     * and Minecraft's GUI scale then multiplies every step into a 2x2 or 3x3
     * block, which is what made the row look chewed. The atlas is authored at
     * 128px per glyph and filtered down instead.
     *
     * <p>The texture is white with a coverage alpha, so {@code color} tints it
     * per button state rather than needing a separate asset per state.
     */
    private void drawIcon(int icon, int centerX, int centerY, int color) {
        mc.getTextureManager().bindTexture(ICONS);

        GlStateManager.enableTexture2D();
        GlStateManager.enableBlend();
        GlStateManager.tryBlendFuncSeparate(770, 771, 1, 0);
        GlStateManager.enableAlpha();
        // A hard alpha cut would eat the antialiased edges this whole change
        // exists to produce. Discard only fully transparent texels.
        GlStateManager.alphaFunc(GL11.GL_GREATER, 0.01F);

        GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MIN_FILTER, GL11.GL_LINEAR);
        GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MAG_FILTER, GL11.GL_LINEAR);
        GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_WRAP_S, GL11.GL_CLAMP);
        GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_WRAP_T, GL11.GL_CLAMP);

        float alpha = ((color >> 24) & 0xFF) / 255.0F;
        float red = ((color >> 16) & 0xFF) / 255.0F;
        float green = ((color >> 8) & 0xFF) / 255.0F;
        float blue = (color & 0xFF) / 255.0F;
        GlStateManager.color(red, green, blue, alpha);

        // Half a cell of inset on the U axis keeps linear filtering from
        // sampling the neighbouring glyph at the cell seam.
        float cell = 1.0F / BUTTON_COUNT;
        float bleed = cell * 0.004F;
        float u0 = icon * cell + bleed;
        float u1 = (icon + 1) * cell - bleed;

        int half = ICON_DRAW_SIZE / 2;
        int left = centerX - half;
        int top = centerY - half;
        int right = left + ICON_DRAW_SIZE;
        int bottom = top + ICON_DRAW_SIZE;

        Tessellator tessellator = Tessellator.getInstance();
        WorldRenderer worldrenderer = tessellator.getWorldRenderer();
        worldrenderer.begin(7, DefaultVertexFormats.POSITION_TEX);
        worldrenderer.pos(left, bottom, 0.0D).tex(u0, 1.0D).endVertex();
        worldrenderer.pos(right, bottom, 0.0D).tex(u1, 1.0D).endVertex();
        worldrenderer.pos(right, top, 0.0D).tex(u1, 0.0D).endVertex();
        worldrenderer.pos(left, top, 0.0D).tex(u0, 0.0D).endVertex();
        tessellator.draw();

        GlStateManager.alphaFunc(GL11.GL_GREATER, 0.1F);
        GlStateManager.color(1.0F, 1.0F, 1.0F, 1.0F);
    }

    private static final class GuiMessage extends GuiScreen {
        private final GuiScreen parent;
        private final String title;
        private final String message;

        private GuiMessage(GuiScreen parent, String title, String message) {
            this.parent = parent;
            this.title = title;
            this.message = message;
        }

        @Override
        public void initGui() {
            buttonList.add(new GuiButton(0, width / 2 - 100, height / 2 + 28, 200, 20,
                    I18n.format("gui.back")));
        }

        @Override
        protected void actionPerformed(GuiButton button) {
            mc.displayGuiScreen(parent);
        }

        @Override
        public void drawScreen(int mouseX, int mouseY, float partialTicks) {
            drawGradientRect(0, 0, width, height, 0xFF050505, 0xFF151515);
            drawCenteredString(fontRendererObj, title, width / 2, height / 2 - 28, 0xFFFFFFFF);
            drawCenteredString(fontRendererObj, message, width / 2, height / 2 - 8, 0xFFAAAAAA);
            super.drawScreen(mouseX, mouseY, partialTicks);
        }
    }
}
