package client.privateclient.events;

public enum CoreEventType {
    CLIENT_START,
    CLIENT_READY,
    CLIENT_SHUTDOWN,
    TICK,
    RENDER,
    WORLD_LOAD,
    WORLD_UNLOAD,
    SESSION_CHANGED,
    PROFILE_CHANGED,
    CONFIGURATION_CHANGED,
    MODULE_ENABLED,
    MODULE_DISABLED,
    CONNECTION_ATTEMPT,
    MULTIPLAYER_BLOCKED,
    SCREENSHOT_CREATED
}
