import type {
  InstalledMod,
  LauncherSnapshot,
  ModSummary,
  PendingOperation,
} from "../types/contracts";

export const demoSnapshot: LauncherSnapshot = {
  appVersion: "1.0.0-preview",
  profile: null,
  launch: {
    state: "IDLE",
    message: "Instancja jest gotowa",
    progress: null,
    canCancel: false,
    errorId: null,
    logPath: null,
  },
  settings: {
    schemaVersion: 1,
    javaPath: "C:\\Program Files\\Eclipse Adoptium\\jdk8\\bin\\javaw.exe",
    memoryMinMb: 1024,
    memoryMaxMb: 4096,
    reducedMotion: false,
    autoUpdateChecks: false,
    downloadConcurrency: 3,
  },
  instance: {
    installed: true,
    healthy: true,
    minecraftVersion: "1.8.9",
    forgeVersion: "11.15.1.2318",
    javaLabel: "Eclipse Temurin 8 · 64-bit",
    pendingOperations: 0,
    lastPlayedAt: "2026-07-28T19:42:00.000Z",
  },
};

export const demoLibrary: ModSummary[] = [
  {
    id: "patcher",
    projectId: "demo-patcher",
    versionId: "patcher-1.8.9-1.8.7",
    name: "Patcher",
    author: "Sk1er",
    description:
      "Zestaw poprawek jakości i wydajności przygotowany dla starszych wersji gry.",
    iconUrl: null,
    version: "1.8.7",
    releaseType: "release",
    downloads: 2_841_921,
    updatedAt: "2025-11-04T10:00:00.000Z",
    minecraftVersion: "1.8.9",
    loader: "forge",
    environment: "client",
    license: "Polyform Shield",
    fileSize: 1_982_464,
    dependencyCount: 0,
    trust: "VERIFIED",
    compatibility: "COMPATIBLE",
    compatibilityReason: null,
    installed: true,
    installedVersion: "1.8.6",
    updateAvailable: true,
    required: false,
  },
  {
    id: "scrollable-tooltips",
    projectId: "demo-scrollable-tooltips",
    versionId: "scrollable-tooltips-1.4",
    name: "Scrollable Tooltips",
    author: "Sk1er",
    description: "Przewijanie zbyt długich opisów przedmiotów bez zasłaniania interfejsu.",
    iconUrl: null,
    version: "1.4",
    releaseType: "release",
    downloads: 744_112,
    updatedAt: "2025-08-19T16:24:00.000Z",
    minecraftVersion: "1.8.9",
    loader: "forge",
    environment: "client",
    license: "BSD-3-Clause",
    fileSize: 187_620,
    dependencyCount: 0,
    trust: "FROM_MODRINTH",
    compatibility: "COMPATIBLE",
    compatibilityReason: null,
    installed: false,
    installedVersion: null,
    updateAvailable: false,
    required: false,
  },
  {
    id: "foamfix-legacy",
    projectId: "demo-foamfix",
    versionId: "foamfix-0.6.3",
    name: "FoamFix Legacy",
    author: "asiekierka",
    description:
      "Optymalizacja wykorzystania pamięci dla instancji Forge z rozbudowanym zestawem modów.",
    iconUrl: null,
    version: "0.6.3",
    releaseType: "release",
    downloads: 1_362_057,
    updatedAt: "2024-12-08T07:13:00.000Z",
    minecraftVersion: "1.8.9",
    loader: "forge",
    environment: "client_and_server",
    license: "LGPL-3.0",
    fileSize: 1_145_288,
    dependencyCount: 1,
    trust: "VERIFIED",
    compatibility: "COMPATIBLE",
    compatibilityReason: null,
    installed: false,
    installedVersion: null,
    updateAvailable: false,
    required: false,
  },
  {
    id: "legacy-animations",
    projectId: "demo-legacy-animations",
    versionId: "legacy-animations-beta-4",
    name: "Legacy Animations",
    author: "Polyfrost",
    description:
      "Subtelne opcje animacji interfejsu i gracza zachowujące charakter wersji 1.8.9.",
    iconUrl: null,
    version: "1.0.0-beta.4",
    releaseType: "beta",
    downloads: 483_205,
    updatedAt: "2026-01-12T09:30:00.000Z",
    minecraftVersion: "1.8.9",
    loader: "forge",
    environment: "client",
    license: "GPL-3.0",
    fileSize: 782_340,
    dependencyCount: 1,
    trust: "FROM_MODRINTH",
    compatibility: "EXPERIMENTAL",
    compatibilityReason: "Dostępne jest wyłącznie wydanie beta.",
    installed: false,
    installedVersion: null,
    updateAvailable: false,
    required: false,
  },
  {
    id: "keystrokes",
    projectId: "demo-keystrokes",
    versionId: "keystrokes-8.0.2",
    name: "Keystrokes",
    author: "JavaW",
    description: "Konfigurowalny, lokalny podgląd klawiszy i kliknięć na ekranie.",
    iconUrl: null,
    version: "8.0.2",
    releaseType: "release",
    downloads: 3_107_080,
    updatedAt: "2025-04-27T14:22:00.000Z",
    minecraftVersion: "1.8.9",
    loader: "forge",
    environment: "client",
    license: "MIT",
    fileSize: 358_732,
    dependencyCount: 0,
    trust: "FROM_MODRINTH",
    compatibility: "COMPATIBLE",
    compatibilityReason: null,
    installed: false,
    installedVersion: null,
    updateAvailable: false,
    required: false,
  },
  {
    id: "fixture-download-failure",
    projectId: "demo-download-error",
    versionId: "fixture-download-error-1.0.0",
    name: "Fixture Download Failure",
    author: "Private Client E2E",
    description: "Jawny fixture deweloperski wywołujący kontrolowany błąd pobierania.",
    iconUrl: null,
    version: "1.0.0",
    releaseType: "release",
    downloads: 0,
    updatedAt: "2026-07-30T16:00:00.000Z",
    minecraftVersion: "1.8.9",
    loader: "forge",
    environment: "client",
    license: "Test fixture",
    fileSize: 524_288,
    dependencyCount: 0,
    trust: "FROM_MODRINTH",
    compatibility: "COMPATIBLE",
    compatibilityReason: null,
    installed: false,
    installedVersion: null,
    updateAvailable: false,
    required: false,
  },
  {
    id: "unknown-license-mod",
    projectId: "demo-license-review",
    versionId: "unknown-license-2.0",
    name: "Minimal HUD",
    author: "ExampleAuthor",
    description:
      "Lekki zestaw elementów HUD. Metadane licencji wymagają ręcznej weryfikacji.",
    iconUrl: null,
    version: "2.0.0",
    releaseType: "release",
    downloads: 22_903,
    updatedAt: "2026-03-08T11:11:00.000Z",
    minecraftVersion: "1.8.9",
    loader: "forge",
    environment: "client",
    license: "Unknown",
    fileSize: 211_500,
    dependencyCount: 0,
    trust: "FROM_MODRINTH",
    compatibility: "LICENSE_REVIEW",
    compatibilityReason: "Licencja projektu nie została jednoznacznie opisana.",
    installed: false,
    installedVersion: null,
    updateAvailable: false,
    required: false,
  },
];

function installedFrom(
  source: ModSummary,
  overrides: Pick<
    InstalledMod,
    "provider" | "fileName" | "sha512" | "installedAt" | "dependencies" | "dependents"
  >,
): InstalledMod {
  return {
    ...source,
    installed: true,
    installedVersion: source.installedVersion ?? source.version,
    ...overrides,
  };
}

export const demoInstalled: InstalledMod[] = [
  installedFrom(
    {
      ...demoLibrary[0]!,
      installedVersion: "1.8.6",
    },
    {
      provider: "modrinth",
      fileName: "Patcher-1.8.6.jar",
      sha512: "4ab9f8d21b95f96b11d183ad1275b67e2dd46a44f049ca50",
      installedAt: "2026-07-22T12:10:00.000Z",
      dependencies: [],
      dependents: [],
    },
  ),
  installedFrom(
    {
      ...demoLibrary[1]!,
      id: "private-optimization",
      projectId: "private-optimization",
      versionId: "private-optimization-1.0.0",
      name: "Private Optimization",
      author: "Private Client",
      description: "Skonsolidowany pakiet optymalizacji wydajności.",
      version: "1.0.0",
      license: "Private Client Source License",
      trust: "VERIFIED",
      required: true,
      installedVersion: "1.0.0",
      updateAvailable: false,
    },
    {
      provider: "private-client",
      fileName: "private-optimization-1.0.0.jar",
      sha512: "8d4638eef73b02b682e825b7805e2b19e5976371a5328291",
      installedAt: "2026-07-22T12:09:00.000Z",
      dependencies: [],
      dependents: [],
    },
  ),
];

export const demoPending: PendingOperation[] = [];
